config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
    resources :messages
    root 'messages#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
    validates :title, presence: true
    validates :body, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def index
        @messages = Message.all.order("created_at DESC")
    end
    def new
        @message = Message.new
    end
    def create
        @message = Message.new(message_params)
        if @message.save
            redirect_to root_path
        else
            render 'new'
        end
    end
    
    
    def show
        @message = Message.find(params[:id])
    end
    def edit
        @message = Message.find(params[:id])
    end
    def update
        @message = Message.find(params[:id])
        @message.update(message_params)
        redirect_to root_path
    
    end
    def destroy
        @message = Message.find(params[:id])
        @message.destroy
        redirect_to root_path
        
    end
    
    private
    
    def message_params
        params.require(:message).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Messageboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    
    <p class="notice"><%=notice%></p>
    <p class="alert"><%=alert%> </p>
    <header>
        <%=link_to "Message Board", root_path%>
    
    <nav>
        <ul>
            <li><%=link_to "SignUp", new_user_registration_path%></li>
            <%if user_signed_in?%>
            <li><%=link_to "SignOut", destroy_user_session_path, method: :delete%></li>
            <%else%>
            <li><%=link_to "SignIn", new_user_session_path%></li>
            <%end%>
            
        </ul>
        <%if user_signed_in?%>
        <li><%=link_to 'New Message', new_message_path%></li>
        <%end%>
    
    </nav>
    </header>
<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f|%>
<%= f.input :title,label: "Message Title" %>
<%= f.input :body %>
<%= f.button :submit%>
<%end%>

app/views/messages/edit.html.erb
<h1>Edit the Message!!</h1>

<%= render 'form'%>

app/views/messages/index.html.erb
<h1>Hi This Is MessageBoard!!</h1>
<% @messages.each do |message|%>
<h3><%= message.title%></h3><b>
<p><%= truncate(message.body, :length => 35)%></p>
<%= link_to "ReadMe", message%>

<%end%>

app/views/messages/new.html.erb
<h1>Create a new message</h1>
<%= render 'form'%>

app/views/messages/show.html.erb
<h1><%= @message.title %></h1>
<p><%= @message.body%></p>
<%if user_signed_in?%>

<%=link_to "EditMessage", edit_message_path%>
<%= link_to "Delete", message_path, method: :delete, data: {confirm: "Are you sure?"}%>

<%end%>